version: '3.8'
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: crs-main-postgres-db
    environment:
      POSTGRES_DB: crs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-app:
    build: ./services/backend-app
    container_name: crs-main-backend-app
    environment:
      - JWT_SECRET=crs_secret_key_2024
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=crs_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres-db:
        condition: service_healthy

  kong:
    image: kong:3.4
    container_name: crs-main-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong:/usr/local/kong/declarative
    ports:
      - "8000:8000"
    depends_on:
      - backend-app

  frontend:
    build: ./services/frontend
    container_name: crs-main-frontend
    ports:
      - "5173:5173"

volumes:
  postgres-data: